# permissions for end users to edit olsconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: olsconfig-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: lightspeed-operator
    app.kubernetes.io/part-of: lightspeed-operator
    app.kubernetes.io/managed-by: kustomize
  name: olsconfig-editor-role
rules:
- apiGroups:
  - ols.openshift.io
  resources:
  - olsconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ols.openshift.io
  resources:
  - olsconfigs/status
  verbs:
  - get
