apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: lightspeed-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: OpenShift Lightspeed Operator
  sourceType: grpc
  image: quay.io/openshift-lightspeed/lightspeed-catalog:internal-preview
  updateStrategy:
    registryPoll:
      interval: 10m
